# WHM MailGuard - Plugin Configuration
# https://github.com/tu-usuario/whm-mailguard

service=whostmgr
url=/cgi/mailguard/index.cgi
acls=any
target=mainwin
entryurl=mailguard/index.cgi
displayname=MailGuard
user=root
searchtext=mailguard brute force fuerza bruta bloqueo seguridad firewall
name=mailguard